// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod toyota {
        pub mod data_transform {
            /// Data transformation utilities for converting Toyota API data to ABRP format
            ///
            /// This component provides pure business logic for transforming vehicle data
            /// from Toyota Connected Services format to A Better Route Planner (ABRP)
            /// telemetry format.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod converter {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// ABRP telemetry record
                #[derive(Clone)]
                pub struct AbrpTelemetry {
                    /// UTC timestamp (Unix seconds)
                    pub utc: i64,
                    /// State of Charge (0-100)
                    pub soc: f64,
                    /// Latitude (optional)
                    pub lat: Option<f64>,
                    /// Longitude (optional)
                    pub lon: Option<f64>,
                    /// Is vehicle charging (optional)
                    pub is_charging: Option<bool>,
                    /// Is vehicle parked (optional)
                    pub is_parked: Option<bool>,
                    /// Odometer reading in km (optional)
                    pub odometer: Option<f64>,
                    /// Estimated battery range in km (optional)
                    pub est_battery_range: Option<f64>,
                    /// API version
                    pub version: _rt::String,
                }
                impl ::core::fmt::Debug for AbrpTelemetry {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("AbrpTelemetry")
                            .field("utc", &self.utc)
                            .field("soc", &self.soc)
                            .field("lat", &self.lat)
                            .field("lon", &self.lon)
                            .field("is-charging", &self.is_charging)
                            .field("is-parked", &self.is_parked)
                            .field("odometer", &self.odometer)
                            .field("est-battery-range", &self.est_battery_range)
                            .field("version", &self.version)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_parse_iso8601_timestamp_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::parse_iso8601_timestamp(_rt::string_lift(bytes0));
                    _rt::as_i64(result1)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_charging_status_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::is_charging_status(_rt::string_lift(bytes0));
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_toyota_to_abrp_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: i32,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: *mut u8,
                    arg9: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len3 = arg9;
                    let bytes3 = _rt::Vec::from_raw_parts(arg8.cast(), len3, len3);
                    let result4 = T::toyota_to_abrp(
                        _rt::string_lift(bytes0),
                        match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg4;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg3.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg5 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg7;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg6.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        _rt::string_lift(bytes3),
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Ok(e) => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                            let AbrpTelemetry {
                                utc: utc6,
                                soc: soc6,
                                lat: lat6,
                                lon: lon6,
                                is_charging: is_charging6,
                                is_parked: is_parked6,
                                odometer: odometer6,
                                est_battery_range: est_battery_range6,
                                version: version6,
                            } = e;
                            *ptr5.add(8).cast::<i64>() = _rt::as_i64(utc6);
                            *ptr5.add(16).cast::<f64>() = _rt::as_f64(soc6);
                            match lat6 {
                                Some(e) => {
                                    *ptr5.add(24).cast::<u8>() = (1i32) as u8;
                                    *ptr5.add(32).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr5.add(24).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match lon6 {
                                Some(e) => {
                                    *ptr5.add(40).cast::<u8>() = (1i32) as u8;
                                    *ptr5.add(48).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr5.add(40).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match is_charging6 {
                                Some(e) => {
                                    *ptr5.add(56).cast::<u8>() = (1i32) as u8;
                                    *ptr5.add(57).cast::<u8>() = (match e {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                                None => {
                                    *ptr5.add(56).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match is_parked6 {
                                Some(e) => {
                                    *ptr5.add(58).cast::<u8>() = (1i32) as u8;
                                    *ptr5.add(59).cast::<u8>() = (match e {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                                None => {
                                    *ptr5.add(58).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match odometer6 {
                                Some(e) => {
                                    *ptr5.add(64).cast::<u8>() = (1i32) as u8;
                                    *ptr5.add(72).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr5.add(64).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match est_battery_range6 {
                                Some(e) => {
                                    *ptr5.add(80).cast::<u8>() = (1i32) as u8;
                                    *ptr5.add(88).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr5.add(80).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec7 = (version6.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(96 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5.add(96).cast::<*mut u8>() = ptr7.cast_mut();
                        }
                        Err(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let vec8 = (e.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr5
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr5.add(8).cast::<*mut u8>() = ptr8.cast_mut();
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_toyota_to_abrp<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(96).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(96 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0.add(8).cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_abrp_telemetry_cabi<T: Guest>(
                    arg0: i64,
                    arg1: f64,
                    arg2: i32,
                    arg3: f64,
                    arg4: i32,
                    arg5: f64,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: f64,
                    arg12: i32,
                    arg13: f64,
                    arg14: *mut u8,
                    arg15: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg15;
                    let bytes0 = _rt::Vec::from_raw_parts(arg14.cast(), len0, len0);
                    let result1 = T::serialize_abrp_telemetry(AbrpTelemetry {
                        utc: arg0,
                        soc: arg1,
                        lat: match arg2 {
                            0 => None,
                            1 => {
                                let e = arg3;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        lon: match arg4 {
                            0 => None,
                            1 => {
                                let e = arg5;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        is_charging: match arg6 {
                            0 => None,
                            1 => {
                                let e = _rt::bool_lift(arg7 as u8);
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        is_parked: match arg8 {
                            0 => None,
                            1 => {
                                let e = _rt::bool_lift(arg9 as u8);
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        odometer: match arg10 {
                            0 => None,
                            1 => {
                                let e = arg11;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        est_battery_range: match arg12 {
                            0 => None,
                            1 => {
                                let e = arg13;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        version: _rt::string_lift(bytes0),
                    });
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_abrp_telemetry<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_abrp_telemetry_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::deserialize_abrp_telemetry(
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let AbrpTelemetry {
                                utc: utc3,
                                soc: soc3,
                                lat: lat3,
                                lon: lon3,
                                is_charging: is_charging3,
                                is_parked: is_parked3,
                                odometer: odometer3,
                                est_battery_range: est_battery_range3,
                                version: version3,
                            } = e;
                            *ptr2.add(8).cast::<i64>() = _rt::as_i64(utc3);
                            *ptr2.add(16).cast::<f64>() = _rt::as_f64(soc3);
                            match lat3 {
                                Some(e) => {
                                    *ptr2.add(24).cast::<u8>() = (1i32) as u8;
                                    *ptr2.add(32).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr2.add(24).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match lon3 {
                                Some(e) => {
                                    *ptr2.add(40).cast::<u8>() = (1i32) as u8;
                                    *ptr2.add(48).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr2.add(40).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match is_charging3 {
                                Some(e) => {
                                    *ptr2.add(56).cast::<u8>() = (1i32) as u8;
                                    *ptr2.add(57).cast::<u8>() = (match e {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                                None => {
                                    *ptr2.add(56).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match is_parked3 {
                                Some(e) => {
                                    *ptr2.add(58).cast::<u8>() = (1i32) as u8;
                                    *ptr2.add(59).cast::<u8>() = (match e {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                                None => {
                                    *ptr2.add(58).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match odometer3 {
                                Some(e) => {
                                    *ptr2.add(64).cast::<u8>() = (1i32) as u8;
                                    *ptr2.add(72).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr2.add(64).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match est_battery_range3 {
                                Some(e) => {
                                    *ptr2.add(80).cast::<u8>() = (1i32) as u8;
                                    *ptr2.add(88).cast::<f64>() = _rt::as_f64(e);
                                }
                                None => {
                                    *ptr2.add(80).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec4 = (version3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(96 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(96).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2.add(8).cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_abrp_telemetry<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(96).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(96 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0.add(8).cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Parse ISO 8601 timestamp to Unix seconds
                    ///
                    /// Examples: "2025-01-15T12:00:00Z", "2025-01-15T12:00:00+00:00"
                    /// Returns current time if parsing fails
                    fn parse_iso8601_timestamp(iso_string: _rt::String) -> i64;
                    /// Determine if vehicle is charging from status string
                    ///
                    /// Returns true if status contains "CHARGING" or "CONNECTED" (case-insensitive)
                    fn is_charging_status(status: _rt::String) -> bool;
                    /// Convert Toyota electric status to ABRP telemetry
                    ///
                    /// Takes JSON strings from toyota-api-types component and converts to ABRP format
                    ///
                    /// Parameters:
                    /// - electric-status-json: ElectricStatusResponse as JSON
                    /// - location-json: Optional LocationResponse as JSON
                    /// - telemetry-json: Optional TelemetryResponse as JSON
                    /// - version: API version string
                    ///
                    /// Returns: ABRP telemetry data or error message
                    fn toyota_to_abrp(
                        electric_status_json: _rt::String,
                        location_json: Option<_rt::String>,
                        telemetry_json: Option<_rt::String>,
                        version: _rt::String,
                    ) -> Result<AbrpTelemetry, _rt::String>;
                    /// Serialize ABRP telemetry to JSON
                    fn serialize_abrp_telemetry(telemetry: AbrpTelemetry) -> _rt::String;
                    /// Deserialize ABRP telemetry from JSON
                    fn deserialize_abrp_telemetry(
                        json: _rt::String,
                    ) -> Result<AbrpTelemetry, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_toyota_data_transform_converter_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "toyota:data-transform/converter@0.1.0#parse-iso8601-timestamp")]
                        unsafe extern "C" fn export_parse_iso8601_timestamp(arg0 : * mut
                        u8, arg1 : usize,) -> i64 { unsafe { $($path_to_types)*::
                        _export_parse_iso8601_timestamp_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "toyota:data-transform/converter@0.1.0#is-charging-status")]
                        unsafe extern "C" fn export_is_charging_status(arg0 : * mut u8,
                        arg1 : usize,) -> i32 { unsafe { $($path_to_types)*::
                        _export_is_charging_status_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "toyota:data-transform/converter@0.1.0#toyota-to-abrp")] unsafe
                        extern "C" fn export_toyota_to_abrp(arg0 : * mut u8, arg1 :
                        usize, arg2 : i32, arg3 : * mut u8, arg4 : usize, arg5 : i32,
                        arg6 : * mut u8, arg7 : usize, arg8 : * mut u8, arg9 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_toyota_to_abrp_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9) } } #[unsafe (export_name =
                        "cabi_post_toyota:data-transform/converter@0.1.0#toyota-to-abrp")]
                        unsafe extern "C" fn _post_return_toyota_to_abrp(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_toyota_to_abrp::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:data-transform/converter@0.1.0#serialize-abrp-telemetry")]
                        unsafe extern "C" fn export_serialize_abrp_telemetry(arg0 : i64,
                        arg1 : f64, arg2 : i32, arg3 : f64, arg4 : i32, arg5 : f64, arg6
                        : i32, arg7 : i32, arg8 : i32, arg9 : i32, arg10 : i32, arg11 :
                        f64, arg12 : i32, arg13 : f64, arg14 : * mut u8, arg15 : usize,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_serialize_abrp_telemetry_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12,
                        arg13, arg14, arg15) } } #[unsafe (export_name =
                        "cabi_post_toyota:data-transform/converter@0.1.0#serialize-abrp-telemetry")]
                        unsafe extern "C" fn _post_return_serialize_abrp_telemetry(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_abrp_telemetry::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "toyota:data-transform/converter@0.1.0#deserialize-abrp-telemetry")]
                        unsafe extern "C" fn export_deserialize_abrp_telemetry(arg0 : *
                        mut u8, arg1 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_deserialize_abrp_telemetry_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:data-transform/converter@0.1.0#deserialize-abrp-telemetry")]
                        unsafe extern "C" fn _post_return_deserialize_abrp_telemetry(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_deserialize_abrp_telemetry::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_toyota_data_transform_converter_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 96 + 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 96
                        + 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_data_transform_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::toyota::data_transform::converter::__export_toyota_data_transform_converter_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::toyota::data_transform::converter);
    };
}
#[doc(inline)]
pub(crate) use __export_data_transform_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:toyota:data-transform@0.1.0:data-transform:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 605] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x03\x01A\x02\x01\
A\x02\x01B\x10\x01ku\x01k\x7f\x01r\x09\x03utcx\x03socu\x03lat\0\x03lon\0\x0bis-c\
harging\x01\x09is-parked\x01\x08odometer\0\x11est-battery-range\0\x07versions\x04\
\0\x0eabrp-telemetry\x03\0\x02\x01@\x01\x0aiso-strings\0x\x04\0\x17parse-iso8601\
-timestamp\x01\x04\x01@\x01\x06statuss\0\x7f\x04\0\x12is-charging-status\x01\x05\
\x01ks\x01j\x01\x03\x01s\x01@\x04\x14electric-status-jsons\x0dlocation-json\x06\x0e\
telemetry-json\x06\x07versions\0\x07\x04\0\x0etoyota-to-abrp\x01\x08\x01@\x01\x09\
telemetry\x03\0s\x04\0\x18serialize-abrp-telemetry\x01\x09\x01@\x01\x04jsons\0\x07\
\x04\0\x1adeserialize-abrp-telemetry\x01\x0a\x04\0%toyota:data-transform/convert\
er@0.1.0\x05\0\x04\0*toyota:data-transform/data-transform@0.1.0\x04\0\x0b\x14\x01\
\0\x0edata-transform\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-comp\
onent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
