pull_request_rules:
  - name: Automatic merge
    description: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success = cargo-checkmate
      - check-success = udeps-check
      - check-success = cargo-deny (advisories)
      - check-success = cargo-deny (bans licenses sources)
    actions:
      merge:
        method: squash
