// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod toyota {
        pub mod metrics {
            /// Prometheus-compatible metrics collection
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod collector {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::record_request(_rt::string_lift(bytes0));
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_error_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::record_error(_rt::string_lift(bytes0));
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_cache_hit_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_cache_hit();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_cache_miss_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_cache_miss();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_login_attempt_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_login_attempt();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_login_failure_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_login_failure();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_increment_active_sessions_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::increment_active_sessions();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_decrement_active_sessions_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::decrement_active_sessions();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_rate_limit_hit_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_rate_limit_hit();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_circuit_breaker_open_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_circuit_breaker_open();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_retry_attempt_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_retry_attempt();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_retry_success_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_retry_success();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_retry_exhausted_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_retry_exhausted();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_export_prometheus_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::export_prometheus();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_export_prometheus<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    /// Record HTTP request to endpoint
                    fn record_request(endpoint: _rt::String) -> ();
                    /// Record error for endpoint
                    fn record_error(endpoint: _rt::String) -> ();
                    /// Record cache hit
                    fn record_cache_hit() -> ();
                    /// Record cache miss
                    fn record_cache_miss() -> ();
                    /// Record login attempt
                    fn record_login_attempt() -> ();
                    /// Record login failure
                    fn record_login_failure() -> ();
                    /// Increment active sessions count
                    fn increment_active_sessions() -> ();
                    /// Decrement active sessions count
                    fn decrement_active_sessions() -> ();
                    /// Record rate limit hit
                    fn record_rate_limit_hit() -> ();
                    /// Record circuit breaker open event
                    fn record_circuit_breaker_open() -> ();
                    /// Record retry attempt
                    fn record_retry_attempt() -> ();
                    /// Record successful retry
                    fn record_retry_success() -> ();
                    /// Record exhausted retry
                    fn record_retry_exhausted() -> ();
                    /// Export metrics in Prometheus text format
                    fn export_prometheus() -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_toyota_metrics_collector_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-request")] unsafe extern
                        "C" fn export_record_request(arg0 : * mut u8, arg1 : usize,) {
                        unsafe { $($path_to_types)*:: _export_record_request_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-error")] unsafe extern "C"
                        fn export_record_error(arg0 : * mut u8, arg1 : usize,) { unsafe {
                        $($path_to_types)*:: _export_record_error_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-cache-hit")] unsafe extern
                        "C" fn export_record_cache_hit() { unsafe { $($path_to_types)*::
                        _export_record_cache_hit_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "toyota:metrics/collector@0.1.0#record-cache-miss")] unsafe
                        extern "C" fn export_record_cache_miss() { unsafe {
                        $($path_to_types)*:: _export_record_cache_miss_cabi::<$ty > () }
                        } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-login-attempt")] unsafe
                        extern "C" fn export_record_login_attempt() { unsafe {
                        $($path_to_types)*:: _export_record_login_attempt_cabi::<$ty > ()
                        } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-login-failure")] unsafe
                        extern "C" fn export_record_login_failure() { unsafe {
                        $($path_to_types)*:: _export_record_login_failure_cabi::<$ty > ()
                        } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#increment-active-sessions")]
                        unsafe extern "C" fn export_increment_active_sessions() { unsafe
                        { $($path_to_types)*::
                        _export_increment_active_sessions_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "toyota:metrics/collector@0.1.0#decrement-active-sessions")]
                        unsafe extern "C" fn export_decrement_active_sessions() { unsafe
                        { $($path_to_types)*::
                        _export_decrement_active_sessions_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "toyota:metrics/collector@0.1.0#record-rate-limit-hit")] unsafe
                        extern "C" fn export_record_rate_limit_hit() { unsafe {
                        $($path_to_types)*:: _export_record_rate_limit_hit_cabi::<$ty >
                        () } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-circuit-breaker-open")]
                        unsafe extern "C" fn export_record_circuit_breaker_open() {
                        unsafe { $($path_to_types)*::
                        _export_record_circuit_breaker_open_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "toyota:metrics/collector@0.1.0#record-retry-attempt")] unsafe
                        extern "C" fn export_record_retry_attempt() { unsafe {
                        $($path_to_types)*:: _export_record_retry_attempt_cabi::<$ty > ()
                        } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-retry-success")] unsafe
                        extern "C" fn export_record_retry_success() { unsafe {
                        $($path_to_types)*:: _export_record_retry_success_cabi::<$ty > ()
                        } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#record-retry-exhausted")] unsafe
                        extern "C" fn export_record_retry_exhausted() { unsafe {
                        $($path_to_types)*:: _export_record_retry_exhausted_cabi::<$ty >
                        () } } #[unsafe (export_name =
                        "toyota:metrics/collector@0.1.0#export-prometheus")] unsafe
                        extern "C" fn export_export_prometheus() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_export_prometheus_cabi::<$ty > () }
                        } #[unsafe (export_name =
                        "cabi_post_toyota:metrics/collector@0.1.0#export-prometheus")]
                        unsafe extern "C" fn _post_return_export_prometheus(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_export_prometheus::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_toyota_metrics_collector_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_metrics_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::toyota::metrics::collector::__export_toyota_metrics_collector_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::toyota::metrics::collector);
    };
}
#[doc(inline)]
pub(crate) use __export_metrics_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:toyota:metrics@0.1.0:metrics:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 574] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc0\x03\x01A\x02\x01\
A\x02\x01B\x11\x01@\x01\x08endpoints\x01\0\x04\0\x0erecord-request\x01\0\x04\0\x0c\
record-error\x01\0\x01@\0\x01\0\x04\0\x10record-cache-hit\x01\x01\x04\0\x11recor\
d-cache-miss\x01\x01\x04\0\x14record-login-attempt\x01\x01\x04\0\x14record-login\
-failure\x01\x01\x04\0\x19increment-active-sessions\x01\x01\x04\0\x19decrement-a\
ctive-sessions\x01\x01\x04\0\x15record-rate-limit-hit\x01\x01\x04\0\x1brecord-ci\
rcuit-breaker-open\x01\x01\x04\0\x14record-retry-attempt\x01\x01\x04\0\x14record\
-retry-success\x01\x01\x04\0\x16record-retry-exhausted\x01\x01\x01@\0\0s\x04\0\x11\
export-prometheus\x01\x02\x04\0\x1etoyota:metrics/collector@0.1.0\x05\0\x04\0\x1c\
toyota:metrics/metrics@0.1.0\x04\0\x0b\x0d\x01\0\x07metrics\x03\0\0\0G\x09produc\
ers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060\
.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
