// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod toyota {
        pub mod validation {
            /// Input validation utilities for user credentials and data
            ///
            /// This component provides pure validation logic for user inputs
            /// including email validation, length checks, and format validation.
            /// Zero dependencies on Spin SDK or platform-specific APIs.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod validator {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Validation configuration constants
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct ValidationConfig {
                    /// Maximum username length (default: 256)
                    pub max_username_length: u32,
                    /// Maximum password length (default: 256)
                    pub max_password_length: u32,
                }
                impl ::core::fmt::Debug for ValidationConfig {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ValidationConfig")
                            .field("max-username-length", &self.max_username_length)
                            .field("max-password-length", &self.max_password_length)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_default_config_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_default_config();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let ValidationConfig {
                        max_username_length: max_username_length2,
                        max_password_length: max_password_length2,
                    } = result0;
                    *ptr1.add(0).cast::<i32>() = _rt::as_i32(max_username_length2);
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(max_password_length2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_credentials_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::validate_credentials(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        ValidationConfig {
                            max_username_length: arg4 as u32,
                            max_password_length: arg5 as u32,
                        },
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(_) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_credentials<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_valid_email_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::is_valid_email(_rt::string_lift(bytes0));
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_string_length_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::validate_string_length(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        arg4 as u32,
                        arg5 as u32,
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(_) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_string_length<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_empty_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::is_empty(_rt::string_lift(bytes0));
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    /// Get default validation configuration
                    fn get_default_config() -> ValidationConfig;
                    /// Validate user credentials (username and password)
                    ///
                    /// Checks:
                    /// - Username is not empty
                    /// - Password is not empty
                    /// - Username length <= max-username-length
                    /// - Password length <= max-password-length
                    /// - Username contains '@' and '.' (basic email format)
                    ///
                    /// Returns: Ok(()) if valid, Err(message) if invalid
                    fn validate_credentials(
                        username: _rt::String,
                        password: _rt::String,
                        config: ValidationConfig,
                    ) -> Result<(), _rt::String>;
                    /// Validate email format (basic check)
                    ///
                    /// Checks that email contains '@' and '.'
                    /// Returns: true if valid, false otherwise
                    fn is_valid_email(email: _rt::String) -> bool;
                    /// Validate string length is within bounds
                    ///
                    /// Returns: Ok(()) if valid, Err(message) if invalid
                    fn validate_string_length(
                        value: _rt::String,
                        field_name: _rt::String,
                        min_length: u32,
                        max_length: u32,
                    ) -> Result<(), _rt::String>;
                    /// Check if string is empty
                    fn is_empty(value: _rt::String) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_toyota_validation_validator_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "toyota:validation/validator@0.1.0#get-default-config")] unsafe
                        extern "C" fn export_get_default_config() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_default_config_cabi::<$ty > () }
                        } #[unsafe (export_name =
                        "toyota:validation/validator@0.1.0#validate-credentials")] unsafe
                        extern "C" fn export_validate_credentials(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : i32, arg5 : i32,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_validate_credentials_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_toyota:validation/validator@0.1.0#validate-credentials")]
                        unsafe extern "C" fn _post_return_validate_credentials(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_validate_credentials::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:validation/validator@0.1.0#is-valid-email")] unsafe
                        extern "C" fn export_is_valid_email(arg0 : * mut u8, arg1 :
                        usize,) -> i32 { unsafe { $($path_to_types)*::
                        _export_is_valid_email_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "toyota:validation/validator@0.1.0#validate-string-length")]
                        unsafe extern "C" fn export_validate_string_length(arg0 : * mut
                        u8, arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : i32, arg5
                        : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_validate_string_length_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_toyota:validation/validator@0.1.0#validate-string-length")]
                        unsafe extern "C" fn _post_return_validate_string_length(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_validate_string_length::<$ty > (arg0) } } #[unsafe
                        (export_name = "toyota:validation/validator@0.1.0#is-empty")]
                        unsafe extern "C" fn export_is_empty(arg0 : * mut u8, arg1 :
                        usize,) -> i32 { unsafe { $($path_to_types)*::
                        _export_is_empty_cabi::<$ty > (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_toyota_validation_validator_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_validation_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::toyota::validation::validator::__export_toyota_validation_validator_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::toyota::validation::validator);
    };
}
#[doc(inline)]
pub(crate) use __export_validation_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:toyota:validation@0.1.0:validation:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 505] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf8\x02\x01A\x02\x01\
A\x02\x01B\x0d\x01r\x02\x13max-username-lengthy\x13max-password-lengthy\x04\0\x11\
validation-config\x03\0\0\x01@\0\0\x01\x04\0\x12get-default-config\x01\x02\x01j\0\
\x01s\x01@\x03\x08usernames\x08passwords\x06config\x01\0\x03\x04\0\x14validate-c\
redentials\x01\x04\x01@\x01\x05emails\0\x7f\x04\0\x0eis-valid-email\x01\x05\x01@\
\x04\x05values\x0afield-names\x0amin-lengthy\x0amax-lengthy\0\x03\x04\0\x16valid\
ate-string-length\x01\x06\x01@\x01\x05values\0\x7f\x04\0\x08is-empty\x01\x07\x04\
\0!toyota:validation/validator@0.1.0\x05\0\x04\0\"toyota:validation/validation@0\
.1.0\x04\0\x0b\x10\x01\0\x0avalidation\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
