// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod toyota {
        pub mod api_types {
            /// Toyota API data type serialization/deserialization helpers
            ///
            /// This component provides pure data models for Toyota Connected Services APIs
            /// including authentication, vehicle data, and telemetry structures.
            /// All types are Serde-compatible and have zero dependencies on Spin SDK.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod models {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_token_response_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                    let result3 = T::serialize_token_response(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        _rt::string_lift(bytes2),
                        arg6 as u32,
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = (result3.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr4.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_token_response<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_token_response_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::deserialize_token_response(
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let (t3_0, t3_1, t3_2, t3_3) = e;
                            let vec4 = (t3_0.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (t3_1.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = (t3_2.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr2
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr2
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                            *ptr2
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(t3_3);
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_token_response<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                        }
                        _ => {
                            let l7 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l7, l8, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_electric_status_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: i32,
                    arg6: f32,
                    arg7: i32,
                    arg8: f32,
                    arg9: i32,
                    arg10: i32,
                    arg11: *mut u8,
                    arg12: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len1 = arg12;
                    let bytes1 = _rt::Vec::from_raw_parts(arg11.cast(), len1, len1);
                    let result2 = T::serialize_electric_status(
                        match arg0 {
                            0 => None,
                            1 => {
                                let e = arg1;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len0 = arg4;
                                    let bytes0 = _rt::Vec::from_raw_parts(
                                        arg3.cast(),
                                        len0,
                                        len0,
                                    );
                                    _rt::string_lift(bytes0)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg5 {
                            0 => None,
                            1 => {
                                let e = arg6;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg7 {
                            0 => None,
                            1 => {
                                let e = arg8;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg9 {
                            0 => None,
                            1 => {
                                let e = arg10;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = (result2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_electric_status<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_electric_status_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::deserialize_electric_status(
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_electric_status<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_vehicle_info_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: i32,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: i32,
                    arg9: *mut u8,
                    arg10: usize,
                    arg11: i32,
                    arg12: *mut u8,
                    arg13: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result5 = T::serialize_vehicle_info(
                        _rt::string_lift(bytes0),
                        match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg4;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg3.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg5 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg7;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg6.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg8 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len3 = arg10;
                                    let bytes3 = _rt::Vec::from_raw_parts(
                                        arg9.cast(),
                                        len3,
                                        len3,
                                    );
                                    _rt::string_lift(bytes3)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        match arg11 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len4 = arg13;
                                    let bytes4 = _rt::Vec::from_raw_parts(
                                        arg12.cast(),
                                        len4,
                                        len4,
                                    );
                                    _rt::string_lift(bytes4)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec7 = (result5.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *ptr6.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr6.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_vehicle_info<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_vehicle_list_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::deserialize_vehicle_list(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_vehicle_list<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_location_cabi<T: Guest>(
                    arg0: f64,
                    arg1: f64,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg3;
                    let bytes0 = _rt::Vec::from_raw_parts(arg2.cast(), len0, len0);
                    let result1 = T::serialize_location(
                        arg0,
                        arg1,
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_location<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_location_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::deserialize_location(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let (t3_0, t3_1, t3_2) = e;
                            *ptr2.add(8).cast::<f64>() = _rt::as_f64(t3_0);
                            *ptr2.add(16).cast::<f64>() = _rt::as_f64(t3_1);
                            let vec4 = (t3_2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(24 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(24).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2.add(8).cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_location<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(24).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(24 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0.add(8).cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_create_auth_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result3 = T::create_auth_request(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        match arg4 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg6;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg5.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = (result3.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr4.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_create_auth_request<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_create_token_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::create_token_request(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_create_token_request<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_create_refresh_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::create_refresh_request(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_create_refresh_request<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_token_expired_cabi<T: Guest>(
                    arg0: i64,
                    arg1: i64,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::is_token_expired(arg0, arg1);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    /// Serialize TokenResponse to JSON
                    fn serialize_token_response(
                        access_token: _rt::String,
                        refresh_token: _rt::String,
                        id_token: _rt::String,
                        expires_in: u32,
                    ) -> _rt::String;
                    /// Deserialize TokenResponse from JSON
                    fn deserialize_token_response(
                        json: _rt::String,
                    ) -> Result<
                        (_rt::String, _rt::String, _rt::String, u32),
                        _rt::String,
                    >;
                    /// Serialize ElectricStatusResponse to JSON
                    fn serialize_electric_status(
                        battery_level: Option<i32>,
                        charging_status: Option<_rt::String>,
                        ev_range: Option<f32>,
                        ev_range_with_ac: Option<f32>,
                        remaining_charge_time: Option<i32>,
                        timestamp: _rt::String,
                    ) -> _rt::String;
                    /// Deserialize ElectricStatusResponse from JSON
                    fn deserialize_electric_status(
                        json: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                    /// Serialize VehicleInfo to JSON
                    fn serialize_vehicle_info(
                        vin: _rt::String,
                        model: Option<_rt::String>,
                        model_name: Option<_rt::String>,
                        model_year: Option<_rt::String>,
                        alias: Option<_rt::String>,
                    ) -> _rt::String;
                    /// Deserialize VehicleListResponse from JSON
                    fn deserialize_vehicle_list(
                        json: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                    /// Serialize LocationResponse to JSON
                    fn serialize_location(
                        lat: f64,
                        lon: f64,
                        timestamp: _rt::String,
                    ) -> _rt::String;
                    /// Deserialize LocationResponse from JSON
                    fn deserialize_location(
                        json: _rt::String,
                    ) -> Result<(f64, f64, _rt::String), _rt::String>;
                    /// Create AuthenticateRequest with credentials
                    fn create_auth_request(
                        username: _rt::String,
                        password: _rt::String,
                        auth_id: Option<_rt::String>,
                    ) -> _rt::String;
                    /// Create TokenRequest for authorization code flow
                    fn create_token_request(code: _rt::String) -> _rt::String;
                    /// Create RefreshTokenRequest
                    fn create_refresh_request(refresh_token: _rt::String) -> _rt::String;
                    /// Check if cached token is expired
                    fn is_token_expired(expires_at: i64, current_time: i64) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_toyota_api_types_models_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "toyota:api-types/models@0.1.0#serialize-token-response")] unsafe
                        extern "C" fn export_serialize_token_response(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8,
                        arg5 : usize, arg6 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_serialize_token_response_cabi::<$ty
                        > (arg0, arg1, arg2, arg3, arg4, arg5, arg6) } } #[unsafe
                        (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#serialize-token-response")]
                        unsafe extern "C" fn _post_return_serialize_token_response(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_token_response::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "toyota:api-types/models@0.1.0#deserialize-token-response")]
                        unsafe extern "C" fn export_deserialize_token_response(arg0 : *
                        mut u8, arg1 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_deserialize_token_response_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#deserialize-token-response")]
                        unsafe extern "C" fn _post_return_deserialize_token_response(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_deserialize_token_response::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "toyota:api-types/models@0.1.0#serialize-electric-status")]
                        unsafe extern "C" fn export_serialize_electric_status(arg0 : i32,
                        arg1 : i32, arg2 : i32, arg3 : * mut u8, arg4 : usize, arg5 :
                        i32, arg6 : f32, arg7 : i32, arg8 : f32, arg9 : i32, arg10 : i32,
                        arg11 : * mut u8, arg12 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_serialize_electric_status_cabi::<$ty
                        > (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9,
                        arg10, arg11, arg12) } } #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#serialize-electric-status")]
                        unsafe extern "C" fn _post_return_serialize_electric_status(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_electric_status::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "toyota:api-types/models@0.1.0#deserialize-electric-status")]
                        unsafe extern "C" fn export_deserialize_electric_status(arg0 : *
                        mut u8, arg1 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_deserialize_electric_status_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#deserialize-electric-status")]
                        unsafe extern "C" fn
                        _post_return_deserialize_electric_status(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_deserialize_electric_status::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "toyota:api-types/models@0.1.0#serialize-vehicle-info")] unsafe
                        extern "C" fn export_serialize_vehicle_info(arg0 : * mut u8, arg1
                        : usize, arg2 : i32, arg3 : * mut u8, arg4 : usize, arg5 : i32,
                        arg6 : * mut u8, arg7 : usize, arg8 : i32, arg9 : * mut u8, arg10
                        : usize, arg11 : i32, arg12 : * mut u8, arg13 : usize,) -> * mut
                        u8 { unsafe { $($path_to_types)*::
                        _export_serialize_vehicle_info_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12,
                        arg13) } } #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#serialize-vehicle-info")]
                        unsafe extern "C" fn _post_return_serialize_vehicle_info(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_vehicle_info::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:api-types/models@0.1.0#deserialize-vehicle-list")] unsafe
                        extern "C" fn export_deserialize_vehicle_list(arg0 : * mut u8,
                        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_deserialize_vehicle_list_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#deserialize-vehicle-list")]
                        unsafe extern "C" fn _post_return_deserialize_vehicle_list(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_deserialize_vehicle_list::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "toyota:api-types/models@0.1.0#serialize-location")] unsafe
                        extern "C" fn export_serialize_location(arg0 : f64, arg1 : f64,
                        arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_serialize_location_cabi::<$ty >
                        (arg0, arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#serialize-location")]
                        unsafe extern "C" fn _post_return_serialize_location(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_location::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:api-types/models@0.1.0#deserialize-location")] unsafe
                        extern "C" fn export_deserialize_location(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_deserialize_location_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#deserialize-location")]
                        unsafe extern "C" fn _post_return_deserialize_location(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_deserialize_location::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:api-types/models@0.1.0#create-auth-request")] unsafe
                        extern "C" fn export_create_auth_request(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : i32, arg5 : * mut
                        u8, arg6 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_create_auth_request_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6) } } #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#create-auth-request")]
                        unsafe extern "C" fn _post_return_create_auth_request(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_create_auth_request::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:api-types/models@0.1.0#create-token-request")] unsafe
                        extern "C" fn export_create_token_request(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_create_token_request_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#create-token-request")]
                        unsafe extern "C" fn _post_return_create_token_request(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_create_token_request::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "toyota:api-types/models@0.1.0#create-refresh-request")] unsafe
                        extern "C" fn export_create_refresh_request(arg0 : * mut u8, arg1
                        : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_create_refresh_request_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_toyota:api-types/models@0.1.0#create-refresh-request")]
                        unsafe extern "C" fn _post_return_create_refresh_request(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_create_refresh_request::<$ty > (arg0) } } #[unsafe
                        (export_name = "toyota:api-types/models@0.1.0#is-token-expired")]
                        unsafe extern "C" fn export_is_token_expired(arg0 : i64, arg1 :
                        i64,) -> i32 { unsafe { $($path_to_types)*::
                        _export_is_token_expired_cabi::<$ty > (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_toyota_api_types_models_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_toyota_api_types_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::toyota::api_types::models::__export_toyota_api_types_models_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::toyota::api_types::models);
    };
}
#[doc(inline)]
pub(crate) use __export_toyota_api_types_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:toyota:api-types@0.1.0:toyota-api-types:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 943] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa8\x06\x01A\x02\x01\
A\x02\x01B\x1f\x01@\x04\x0caccess-tokens\x0drefresh-tokens\x08id-tokens\x0aexpir\
es-iny\0s\x04\0\x18serialize-token-response\x01\0\x01o\x04sssy\x01j\x01\x01\x01s\
\x01@\x01\x04jsons\0\x02\x04\0\x1adeserialize-token-response\x01\x03\x01kz\x01ks\
\x01kv\x01@\x06\x0dbattery-level\x04\x0fcharging-status\x05\x08ev-range\x06\x10e\
v-range-with-ac\x06\x15remaining-charge-time\x04\x09timestamps\0s\x04\0\x19seria\
lize-electric-status\x01\x07\x01j\x01s\x01s\x01@\x01\x04jsons\0\x08\x04\0\x1bdes\
erialize-electric-status\x01\x09\x01@\x05\x03vins\x05model\x05\x0amodel-name\x05\
\x0amodel-year\x05\x05alias\x05\0s\x04\0\x16serialize-vehicle-info\x01\x0a\x04\0\
\x18deserialize-vehicle-list\x01\x09\x01@\x03\x03latu\x03lonu\x09timestamps\0s\x04\
\0\x12serialize-location\x01\x0b\x01o\x03uus\x01j\x01\x0c\x01s\x01@\x01\x04jsons\
\0\x0d\x04\0\x14deserialize-location\x01\x0e\x01@\x03\x08usernames\x08passwords\x07\
auth-id\x05\0s\x04\0\x13create-auth-request\x01\x0f\x01@\x01\x04codes\0s\x04\0\x14\
create-token-request\x01\x10\x01@\x01\x0drefresh-tokens\0s\x04\0\x16create-refre\
sh-request\x01\x11\x01@\x02\x0aexpires-atx\x0ccurrent-timex\0\x7f\x04\0\x10is-to\
ken-expired\x01\x12\x04\0\x1dtoyota:api-types/models@0.1.0\x05\0\x04\0'toyota:ap\
i-types/toyota-api-types@0.1.0\x04\0\x0b\x16\x01\0\x10toyota-api-types\x03\0\0\0\
G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindge\
n-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
