// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod toyota {
        pub mod retry {
            /// Retry strategy utilities for exponential backoff and retry decisions
            ///
            /// This component provides pure retry logic including exponential backoff
            /// calculation and retry decision making. Zero dependencies on Spin SDK
            /// or any platform-specific APIs.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod strategy {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Retry configuration for exponential backoff
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct RetryConfig {
                    /// Maximum number of retry attempts
                    pub max_attempts: u32,
                    /// Initial delay in milliseconds
                    pub initial_delay_ms: u64,
                    /// Maximum delay in milliseconds (cap for exponential growth)
                    pub max_delay_ms: u64,
                    /// Multiplier for exponential backoff (typically 2.0)
                    pub multiplier: f64,
                }
                impl ::core::fmt::Debug for RetryConfig {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("RetryConfig")
                            .field("max-attempts", &self.max_attempts)
                            .field("initial-delay-ms", &self.initial_delay_ms)
                            .field("max-delay-ms", &self.max_delay_ms)
                            .field("multiplier", &self.multiplier)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_default_config_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_default_config();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let RetryConfig {
                        max_attempts: max_attempts2,
                        initial_delay_ms: initial_delay_ms2,
                        max_delay_ms: max_delay_ms2,
                        multiplier: multiplier2,
                    } = result0;
                    *ptr1.add(0).cast::<i32>() = _rt::as_i32(max_attempts2);
                    *ptr1.add(8).cast::<i64>() = _rt::as_i64(initial_delay_ms2);
                    *ptr1.add(16).cast::<i64>() = _rt::as_i64(max_delay_ms2);
                    *ptr1.add(24).cast::<f64>() = _rt::as_f64(multiplier2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_calculate_backoff_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i64,
                    arg3: i64,
                    arg4: f64,
                ) -> i64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::calculate_backoff(
                        arg0 as u32,
                        RetryConfig {
                            max_attempts: arg1 as u32,
                            initial_delay_ms: arg2 as u64,
                            max_delay_ms: arg3 as u64,
                            multiplier: arg4,
                        },
                    );
                    _rt::as_i64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_should_retry_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::should_retry(
                        _rt::string_lift(bytes0),
                        arg2 as u32,
                        arg3 as u32,
                    );
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_retryable_status_cabi<T: Guest>(
                    arg0: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::is_retryable_status(arg0 as u32);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_has_exceeded_max_attempts_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::has_exceeded_max_attempts(arg0 as u32, arg1 as u32);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    /// Get default retry configuration
                    ///
                    /// Returns:
                    /// - max-attempts: 3
                    /// - initial-delay-ms: 100
                    /// - max-delay-ms: 10000
                    /// - multiplier: 2.0
                    fn get_default_config() -> RetryConfig;
                    /// Calculate exponential backoff delay for a given attempt
                    ///
                    /// Formula: min(initial_delay * multiplier^(attempt-1), max_delay)
                    ///
                    /// Example: With default config (initial=100ms, multiplier=2.0, max=10s):
                    /// - Attempt 1: 100ms
                    /// - Attempt 2: 200ms
                    /// - Attempt 3: 400ms
                    /// - Attempt 4: 800ms
                    /// - etc.
                    ///
                    /// Returns: Delay in milliseconds
                    fn calculate_backoff(attempt: u32, config: RetryConfig) -> u64;
                    /// Determine if a request should be retried
                    ///
                    /// Checks:
                    /// - Have we exceeded max attempts?
                    /// - Is the error retryable? (5xx yes, 4xx no)
                    /// - Is circuit breaker open? (don't retry)
                    ///
                    /// Parameters:
                    /// - error-message: Error description (e.g., "HTTP 503", "Circuit breaker is OPEN")
                    /// - attempt: Current attempt number (1-based)
                    /// - max-attempts: Maximum allowed attempts
                    ///
                    /// Returns: true if should retry, false otherwise
                    fn should_retry(
                        error_message: _rt::String,
                        attempt: u32,
                        max_attempts: u32,
                    ) -> bool;
                    /// Check if an HTTP status code is retryable
                    ///
                    /// Retryable: 5xx (server errors), 429 (too many requests)
                    /// Not retryable: 4xx (client errors), 2xx/3xx (success)
                    ///
                    /// Returns: true if retryable, false otherwise
                    fn is_retryable_status(status_code: u32) -> bool;
                    /// Check if we've exceeded max attempts
                    fn has_exceeded_max_attempts(
                        attempt: u32,
                        max_attempts: u32,
                    ) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_toyota_retry_strategy_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "toyota:retry/strategy@0.1.0#get-default-config")] unsafe extern
                        "C" fn export_get_default_config() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_default_config_cabi::<$ty > () }
                        } #[unsafe (export_name =
                        "toyota:retry/strategy@0.1.0#calculate-backoff")] unsafe extern
                        "C" fn export_calculate_backoff(arg0 : i32, arg1 : i32, arg2 :
                        i64, arg3 : i64, arg4 : f64,) -> i64 { unsafe {
                        $($path_to_types)*:: _export_calculate_backoff_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4) } } #[unsafe (export_name =
                        "toyota:retry/strategy@0.1.0#should-retry")] unsafe extern "C" fn
                        export_should_retry(arg0 : * mut u8, arg1 : usize, arg2 : i32,
                        arg3 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_should_retry_cabi::<$ty > (arg0, arg1, arg2, arg3) } }
                        #[unsafe (export_name =
                        "toyota:retry/strategy@0.1.0#is-retryable-status")] unsafe extern
                        "C" fn export_is_retryable_status(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_is_retryable_status_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "toyota:retry/strategy@0.1.0#has-exceeded-max-attempts")] unsafe
                        extern "C" fn export_has_exceeded_max_attempts(arg0 : i32, arg1 :
                        i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_has_exceeded_max_attempts_cabi::<$ty > (arg0, arg1) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_toyota_retry_strategy_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 32]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 32],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_retry_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::toyota::retry::strategy::__export_toyota_retry_strategy_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::toyota::retry::strategy);
    };
}
#[doc(inline)]
pub(crate) use __export_retry_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:toyota:retry@0.1.0:retry:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 505] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfd\x02\x01A\x02\x01\
A\x02\x01B\x0c\x01r\x04\x0cmax-attemptsy\x10initial-delay-msw\x0cmax-delay-msw\x0a\
multiplieru\x04\0\x0cretry-config\x03\0\0\x01@\0\0\x01\x04\0\x12get-default-conf\
ig\x01\x02\x01@\x02\x07attempty\x06config\x01\0w\x04\0\x11calculate-backoff\x01\x03\
\x01@\x03\x0derror-messages\x07attempty\x0cmax-attemptsy\0\x7f\x04\0\x0cshould-r\
etry\x01\x04\x01@\x01\x0bstatus-codey\0\x7f\x04\0\x13is-retryable-status\x01\x05\
\x01@\x02\x07attempty\x0cmax-attemptsy\0\x7f\x04\0\x19has-exceeded-max-attempts\x01\
\x06\x04\0\x1btoyota:retry/strategy@0.1.0\x05\0\x04\0\x18toyota:retry/retry@0.1.\
0\x04\0\x0b\x0b\x01\0\x05retry\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
