// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod toyota {
        pub mod circuit_breaker {
            /// Circuit breaker pattern for resilient API calls
            ///
            /// Protects against cascading failures when downstream services are unavailable.
            /// Implements the classic three-state circuit breaker: Closed → Open → Half-Open
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod breaker {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Circuit breaker states
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum CircuitState {
                    /// Normal operation - requests are allowed
                    Closed,
                    /// Too many failures - requests fail fast without trying
                    Open,
                    /// Testing if service recovered - limited requests allowed
                    HalfOpen,
                }
                impl ::core::fmt::Debug for CircuitState {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            CircuitState::Closed => {
                                f.debug_tuple("CircuitState::Closed").finish()
                            }
                            CircuitState::Open => {
                                f.debug_tuple("CircuitState::Open").finish()
                            }
                            CircuitState::HalfOpen => {
                                f.debug_tuple("CircuitState::HalfOpen").finish()
                            }
                        }
                    }
                }
                impl CircuitState {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> CircuitState {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => CircuitState::Closed,
                            1 => CircuitState::Open,
                            2 => CircuitState::HalfOpen,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Error when circuit breaker is open
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct BreakerError {
                    /// Seconds until retry is allowed
                    pub retry_after_seconds: u64,
                }
                impl ::core::fmt::Debug for BreakerError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("BreakerError")
                            .field("retry-after-seconds", &self.retry_after_seconds)
                            .finish()
                    }
                }
                impl ::core::fmt::Display for BreakerError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for BreakerError {}
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_can_attempt_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::can_attempt();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let BreakerError {
                                retry_after_seconds: retry_after_seconds2,
                            } = e;
                            *ptr1.add(8).cast::<i64>() = _rt::as_i64(
                                retry_after_seconds2,
                            );
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_success_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_success();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_record_failure_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::record_failure();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_state_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_state();
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_failure_count_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_failure_count();
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    /// Check if a request should be allowed through the circuit breaker
                    /// Returns error with retry-after if circuit is open
                    fn can_attempt() -> Result<(), BreakerError>;
                    /// Record a successful call
                    fn record_success() -> ();
                    /// Record a failed call
                    fn record_failure() -> ();
                    /// Get current circuit breaker state (for monitoring)
                    fn get_state() -> CircuitState;
                    /// Get current failure count (for monitoring)
                    fn get_failure_count() -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_toyota_circuit_breaker_breaker_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "toyota:circuit-breaker/breaker@0.1.0#can-attempt")] unsafe
                        extern "C" fn export_can_attempt() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_can_attempt_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "toyota:circuit-breaker/breaker@0.1.0#record-success")] unsafe
                        extern "C" fn export_record_success() { unsafe {
                        $($path_to_types)*:: _export_record_success_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "toyota:circuit-breaker/breaker@0.1.0#record-failure")] unsafe
                        extern "C" fn export_record_failure() { unsafe {
                        $($path_to_types)*:: _export_record_failure_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "toyota:circuit-breaker/breaker@0.1.0#get-state")] unsafe extern
                        "C" fn export_get_state() -> i32 { unsafe { $($path_to_types)*::
                        _export_get_state_cabi::<$ty > () } } #[unsafe (export_name =
                        "toyota:circuit-breaker/breaker@0.1.0#get-failure-count")] unsafe
                        extern "C" fn export_get_failure_count() -> i32 { unsafe {
                        $($path_to_types)*:: _export_get_failure_count_cabi::<$ty > () }
                        } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_toyota_circuit_breaker_breaker_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 16]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_circuit_breaker_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::toyota::circuit_breaker::breaker::__export_toyota_circuit_breaker_breaker_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::toyota::circuit_breaker::breaker);
    };
}
#[doc(inline)]
pub(crate) use __export_circuit_breaker_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:toyota:circuit-breaker@0.1.0:circuit-breaker:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 505] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf3\x02\x01A\x02\x01\
A\x02\x01B\x10\x01m\x03\x06closed\x04open\x09half-open\x04\0\x0dcircuit-state\x03\
\0\0\x01r\x03\x11failure-thresholdy\x0ftimeout-secondsw\x11success-thresholdy\x04\
\0\x06config\x03\0\x02\x01r\x01\x13retry-after-secondsw\x04\0\x0dbreaker-error\x03\
\0\x04\x01j\0\x01\x05\x01@\0\0\x06\x04\0\x0bcan-attempt\x01\x07\x01@\0\x01\0\x04\
\0\x0erecord-success\x01\x08\x04\0\x0erecord-failure\x01\x08\x01@\0\0\x01\x04\0\x09\
get-state\x01\x09\x01@\0\0y\x04\0\x11get-failure-count\x01\x0a\x04\0$toyota:circ\
uit-breaker/breaker@0.1.0\x05\0\x04\0,toyota:circuit-breaker/circuit-breaker@0.1\
.0\x04\0\x0b\x15\x01\0\x0fcircuit-breaker\x03\0\0\0G\x09producers\x01\x0cprocess\
ed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
